### PR TITLE
VMmanager merging

### PR DESCRIPTION
**Pull request by dmitry-erin**
Pull request for adding vmmanager project to the vmd repo

### CODE REVIEW

**Comment by juliuskoskela** [comment]
@vilvo @baz2142 Should we merge this for now and create a separate repo later or...?

**Review by juliuskoskela — CHANGES_REQUESTED** [review]
- Please re-fetch main to https://github.com/tiiuae/vmd/tree/10-merging-client-app and put client code inside `vmd-client` folder (we recently merged a new structure to main).
- Add instructions to Readme on how to run tests or an example (if there are).
- Document these QT dependencies in a file such as `dependencies.txt`: `qt5-make`, `qtbase5-dev` and `qtdeclarative5-dev`. Later I will incorporate them into a nix-based developer environment.

**Comment by dmitry-erin** [comment]
I already have flake.nix file with dependencies listed there. Is it needed or not?

**Comment by juliuskoskela** [comment]
> I already have flake.nix file with dependencies listed there. Is it needed or not?

I didn't realize. That's all good then!

**Review by juliuskoskela — APPROVED** [review]

**Comment by juliuskoskela** [comment]
I've approved. Maybe add @baz2142 as reviewer as well. I didn't look deeply into the C++, but it builds and runs on my system and the structure is as requested.

**Review by baz2142 — APPROVED** [review]

**Pull request merged**
