### PR TITLE
Merging client app to main 

### LINKED ISSUE #10: Merging client app
Merging client app to the vmd repo as it was proposed on the Monday's meeting

### PR DESCRIPTION
**Pull request by dmitry-erin**
This is pull request to merge client code to main branch. No changes since previous pull request from my fork.

### CODE REVIEW

**Review by baz2142 — APPROVED** [review]

**Review by juliuskoskela — APPROVED** [review]
Compiles and runs

**Comment by juliuskoskela** [comment]
Which Makefile rule cleans all build artifacts and binaries? `make clean` leaves the binary and there is no `make fclean` rule.

**Review by juliuskoskela — CHANGES_REQUESTED** [review]
Clarification on Makefile rules.

- Which rule cleans all build artifacts and binaires making repo ready for a commit? `make clean` leaves the binary and there is no `make fclean`.
- Why does `make distclean` remove the Makefile itself?

**Comment by dmitry-erin** [comment]
> Clarification on Makefile rules.
> 
> * Which rule cleans all build artifacts and binaires making repo ready for a commit? `make clean` leaves the binary and there is no `make fclean`.
> * Why does `make distclean` remove the Makefile itself?

Makefile here is a temp file generated by qmake. `make distclean` removes binary for me

**Comment by juliuskoskela** [comment]
> > Clarification on Makefile rules.
> > 
> > * Which rule cleans all build artifacts and binaires making repo ready for a commit? `make clean` leaves the binary and there is no `make fclean`.
> > * Why does `make distclean` remove the Makefile itself?
> 
> Makefile here is a temp file generated by qmake. `make distclean` removes binary for me

Thanks for clarification. Can you specify what is the correct way to build the program?

**Comment by juliuskoskela** [comment]
If the Makefile is a build artifact from qmake I think it should be .gitignored. or at least it would like to delete itself

```
distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile
```

**Comment by vilvo** [comment]
> If the Makefile is a build artifact from qmake I think it should be .gitignored. or at least it would like to delete itself
> 
> ```
> distclean: clean 
> 	-$(DEL_FILE) $(TARGET) 
> 	-$(DEL_FILE) .qmake.stash
> 	-$(DEL_FILE) Makefile
> ```

Agreed. The client `flake.nix` defines the buildPhase:
```
buildPhase = "qmake; make";
```
where `qmake` generates the Makefile so we have no reason to store the `Makefile` under version control. Adding it to `.gitignore` is also a good idea.

**Comment by dmitry-erin** [comment]
I am going to close this pull request and delete fork. There is no (right and painless) way to sign the prev commits.

**Pull request closed without merging**
